--- 
services: 
  mongo: 
    image: mongo
    volumes: 
      - "$HOME/.deepforge/data:/data/db"
  server: 
    environment: 
      - "MONGO_URI=mongodb://mongo:27017/deepforge"
    image: deepforge/demo-server
    ports: 
      - "8888:8888"
    volumes: 
      - "$HOME/.deepforge/blob:/data/blob"
    depends_on:
      - mongo
  worker: 
    command: "http://server:8888"
    image: deepforge/worker
    depends_on:
      - server
version: "2"
